language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 2.1.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - david.e.santoso@gmail.com
      - marius.butuc@gmail.com
    on_failure: change
    on_success: never
